// // import { Geist, Geist_Mono } from "next/font/google";
// // import "./globals.css";
// // import { AuthProvider } from "./context/AuthContext";
// // // import Navbar from "./components/Navbar";
// // import Navbar from "@/components/Navbar";
// // // import LoginSignupForm from "@/app/signup/page"
// // const geistSans = Geist({
// //   variable: "--font-geist-sans",
// //   subsets: ["latin"],
// // });

// // const geistMono = Geist_Mono({
// //   variable: "--font-geist-mono",
// //   subsets: ["latin"],
// // });

// // export const metadata = {
// //   title: "Bitlinks - Your trusted URL shortener",
// //   description: "Generated by create next app",
// // };

// // export default function RootLayout({ children }) {
// //   return (
// //     <html lang="en">
// //       <body
// //         className={`${geistSans.variable} ${geistMono.variable} antialiased bg-purple-80`}
// //       > 
// //         <AuthProvider>
// //           <Navbar />
// //           {children}
// //         </AuthProvider>
// //       </body>
// //     </html>
// //   );
// // }
 
// // import "./globals.css";

// // export default function RootLayout({ children }) {
// //   return (
// //     <html lang="en">
// //       <body className="antialiased bg-purple-80">
// //         <AuthProvider>
// //           <Navbar />
// //           {children}
// //         </AuthProvider>
// //       </body>
// //     </html>
// //   );
// // }
// import { Inter } from "next/font/google";
// import "./globals.css";
// import { AuthProvider } from "./context/AuthContext";
// import Navbar from "@/components/Navbar";

// const inter = Inter({
//   variable: "--font-inter",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Bitlinks - Your trusted URL shortener",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={`${inter.variable} antialiased bg-purple-80`}>
//         <AuthProvider>
//           <Navbar />
//           {children}
//         </AuthProvider>
//       </body>
//     </html>
//   );
// }
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/context/AuthContext"; 
import Navbar from "@/components/Navbar";
import LoginSignupForm from "@/components/LoginSignupForm";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

// Metadata stays outside of any 'use client' scope
export const metadata = {
  title: "Bitlinks - Your trusted URL shortener",
  description: "Generated by create next app",
};

// ConditionalWrapper moved to a separate client component
import ConditionalWrapper from "@/components/ConditionalWrapper";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased bg-purple-80`}>
        <AuthProvider>
          <Navbar/>
          <ConditionalWrapper>{children}</ConditionalWrapper>
        </AuthProvider>
      </body>
    </html>
  );
}
